03 PL/WebApplication/Pages/Cart.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Belcukerkka.Models.Entities;
using Belcukerkka.Models.Enums;
using Belcukerkka.Models.ViewModels;
using Belcukerkka.Repositories.Interfaces;
using Belcukerkka.Services;
using Belcukerkka.TelegramNotifier;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication.Pages
{
    public class CartModel : PageModel
    {
        private readonly IEntityRepository<Box> _boxRepository;
        private readonly IEntityRepository<Customer> _customerRepository;
        private readonly IEntityRepository<Order> _orderRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CartModel(IEntityRepository<Box> boxRepository,
            IEntityRepository<Customer> customerRepository,
            IEntityRepository<Order> orderRepository,
            IWebHostEnvironment webHostEnvironment)
        {
            _boxRepository = boxRepository;
            _customerRepository = customerRepository;
            _orderRepository = orderRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        public List<CartItemViewModel> CartItems { get; set; }

        [BindProperty]
        public Customer Customer { get; set; }

        public int ItemsCount { get; set; }

        public IActionResult OnGet()
        {
            if (_webHostEnvironment.EnvironmentName == "Staging" && !User.Identity.IsAuthenticated)
                return RedirectToPage("/Maintain");

            CartItems = SessionHandler.GetObjectFromJson<List<CartItemViewModel>>(HttpContext.Session, "Cart");

            if (CartItems == null)
                CartItems = new List<CartItemViewModel>();

            Customer = new Customer();
            ItemsCount = CartItems.Count();

            return Page();
        }

        public IActionResult OnPostAddToCart(int boxId, int amount)
        {
            var box = _boxRepository.GetWithDependencies(boxId);
            var item = new CartItemViewModel() { Box = box, Amount = amount };

            CartItems = SessionHandler.GetObjectFromJson<List<CartItemViewModel>>(HttpContext.Session, "Cart");

            if (CartItems == null)
            {
                CartItems = new List<CartItemViewModel>();
                CartItems.Add(item);
            }
            else
            {
                var index = GetBoxIndex(CartItems, boxId);

                if (index == -1)
                    CartItems.Add(item);
                else
                    CartItems[index].Amount += amount;
            }

            SessionHandler.SetObjectAsJson(HttpContext.Session, "Cart", CartItems);

            return RedirectToPage("/Catalog/Item", new { boxId = boxId });
        }

        public void OnPostRemoveProductFromCart(int itemId)
        {
            CartItems = SessionHandler.GetObjectFromJson<List<CartItemViewModel>>(HttpContext.Session, "Cart");
            CartItems.Remove(CartItems[itemId]);

            SessionHandler.SetObjectAsJson(HttpContext.Session, "Cart", CartItems);
        }

        public void OnPostChangeProductQuantity(int itemId, int newQuantity)
        {
            CartItems = SessionHandler.GetObjectFromJson<List<CartItemViewModel>>(HttpContext.Session, "Cart");
            CartItems[itemId].Amount = newQuantity;

            SessionHandler.SetObjectAsJson(HttpContext.Session, "Cart", CartItems);
        }

        public async Task<IActionResult> OnPostOrder()
        {
            var customer = _customerRepository.GetAll()
                .Where(c => c.Name == Customer.Name && c.Phone == Customer.Phone && c.Type == Customer.Type)
                .Where(c => c.Address != null && c.Address == Customer.Address)
                .FirstOrDefault();

            if (customer == null)
                customer = _customerRepository.Create(Customer);

            Order order = new Order();
            CartItems = SessionHandler.GetObjectFromJson<List<CartItemViewModel>>(HttpContext.Session, "Cart");

            order.Customer = customer;

            if (User.Identity.IsAuthenticated)
                order.CreatedBy = OrderCreatedBy.Admin;
            else
                order.CreatedBy = OrderCreatedBy.User;

            foreach (var item in CartItems)
            {
                var box = _boxRepository.Get(item.Box.Id);

                order.OrderItems.Add(new OrderItem()
                {
                    Box = box,
                    Amount = item.Amount
                });
            }

            order = _orderRepository.Create(order);
            order = _orderRepository.GetWithDependencies(order.Id);

            var notifier = new OrderConfirmedSender();
            await notifier.SendOrderConfirmationMessageAsync(order);

            SessionHandler.ClearSessionObject(HttpContext.Session, "Cart");

            return RedirectToPage("/Catalog/Index");
        }

        public IActionResult OnPostCheckCart()
        {
            CartItems = SessionHandler.GetObjectFromJson<List<CartItemViewModel>>(HttpContext.Session, "Cart");

            bool isCartEmpty;

            if (CartItems == null || CartItems?.Count == 0)
                isCartEmpty = true;
            else
                isCartEmpty = false;

            JsonResult json = new JsonResult(new { isEmpty = isCartEmpty });

            return json;
        }

        private int GetBoxIndex(List<CartItemViewModel> list, int boxId)
        {
            int index;

            var checkExistance = list.Any(ci => ci.Box.Id == boxId);

            if (checkExistance)
            {
                var box = list.FirstOrDefault(ci => ci.Box.Id == boxId);
                index = list.IndexOf(box);
            }
            else
                index = -1;

            return index;
        }
    }
}

03 PL/WebApplication/Pages/Catalog/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Belcukerkka.Models.Entities;
using Belcukerkka.Models.ViewModels;
using Belcukerkka.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Belcukerkka.Services;
using Microsoft.AspNetCore.Hosting;

namespace WebApplication.Pages.Catalog
{
    public class IndexModel : PageModel
    {
        public IndexModel(ICatalogItemRepository catalogItemRepository,
            IPartialToStringRenderer partialToStringRenderer,
            IEntityRepository<Composition> compositionRepository,
            IEntityRepository<Box> boxRepository,
            IWebHostEnvironment webHostEnvironment)
        {
            _catalogItemRepository = catalogItemRepository;
            _partialToStringRenderer = partialToStringRenderer;
            _compositionRepository = compositionRepository;
            _boxRepository = boxRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        private readonly ICatalogItemRepository _catalogItemRepository;
        private readonly IPartialToStringRenderer _partialToStringRenderer;
        private readonly IEntityRepository<Composition> _compositionRepository;
        private readonly IEntityRepository<Box> _boxRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public IEnumerable<CatalogItemViewModel> CatalogItems { get; set; }

        public IEnumerable<int> AvailableWeights { get; set; }

        private int ItemsToLoadCount { get; } = 12;

        public double MinPrice { get; set; }
        public double MaxPrice { get; set; }
        public bool EveryItemIsLoaded { get; set; }

        public IActionResult OnGet(int[] weights, double minPrice, double maxPrice)
        {
            if (_webHostEnvironment.EnvironmentName == "Staging" && !User.Identity.IsAuthenticated)
                return RedirectToPage("/Maintain");

            CatalogItems = new List<CatalogItemViewModel>();
            var catalogItems = _catalogItemRepository.GetAll();

            ViewData["IsFiltered"] = false;

            using (var handler = new CatalogFiltersHandler(_compositionRepository, _boxRepository))
            {
                AvailableWeights = handler.GetAvailableWeights()
                    .OrderBy(w => w)
                    .ToList();

                handler.GetMinAndMaxPrices(out double minPriceAvailable, out double maxPriceAvailable);
                MinPrice = minPriceAvailable;
                MaxPrice = maxPriceAvailable;
            }

            foreach (var item in catalogItems)
            {
                var model = CatalogItemConverter.ConvertSingleCatalogItem(item);

                CatalogItems = CatalogItems.Append(model);
            }

            FilterResults(weights, minPrice, maxPrice);

            int totalItems = CatalogItems.Count();

            CatalogItems = CatalogItems.OrderBy(ci => ci.Id)
                .ThenBy(ci => ci.Weight)
                .Take(ItemsToLoadCount);

            EveryItemIsLoaded = totalItems <= CatalogItems.Count();

            return Page();
        }

        public async Task<IActionResult> OnPostLoadMore(int size, int[] weights, double minPrice, double maxPrice)
        {
            int itemsCount = _catalogItemRepository.GetAll().Count();

            CatalogItems = new List<CatalogItemViewModel>();
            IEnumerable<CatalogItem> catalogItems = _catalogItemRepository.GetAll();
            
            foreach (var item in catalogItems)
            {
                var viewModel = CatalogItemConverter.ConvertSingleCatalogItem(item);

                CatalogItems = CatalogItems.Append(viewModel);
            }

            FilterResults(weights, minPrice, maxPrice);

            CatalogItems = CatalogItems.OrderBy(ci => ci.Id)
                .ThenBy(ci => ci.Weight)
                .Skip(size)
                .Take(ItemsToLoadCount);

            IEnumerable<string> itemsToLoad = new List<string>();

            foreach (var item in CatalogItems)
            {
                string partialView = await _partialToStringRenderer
                    .RenderPartialToStringAsync("_DisplayCatalogItemPartial", item);

                itemsToLoad = itemsToLoad.Append(partialView);
            }

            JsonResult json = new JsonResult(new { ItemsToLoad = itemsToLoad, ItemsCount = itemsCount });

            return json;
        }

        private void FilterResults(int[] weights, double minPrice, double maxPrice)
        {
            if (weights.Length != 0)
            {
                CatalogItems = CatalogItems.Where(ci => weights.Contains(ci.Weight));
                ViewData["WeightsFilter"] = weights;
                ViewData["IsFiltered"] = true;
            }

            if (minPrice != 0)
            {
                IEnumerable<CatalogItemViewModel> list = new List<CatalogItemViewModel>();

                foreach (var parent in CatalogItems)
                {
                    foreach (var child in parent.Children)
                    {
                        if (child.Price >= minPrice)
                        {
                            list = list.Append(parent);
                        }
                    }
                }

                CatalogItems = list.Distinct();
                ViewData["MinPriceFilter"] = minPrice;
                ViewData["IsFiltered"] = true;
            }

            if (maxPrice != 0)
            {
                IEnumerable<CatalogItemViewModel> list = new List<CatalogItemViewModel>();

                foreach (var parent in CatalogItems)
                {
                    foreach (var child in parent.Children)
                    {
                        if (child.Price <= maxPrice)
                        {
                            list = list.Append(parent);
                        }
                    }
                }

                CatalogItems = list.Distinct();
                ViewData["MaxPriceFilter"] = maxPrice;
                ViewData["IsFiltered"] = true;
            }
        }
    }
}

03 PL/WebApplication/Pages/Catalog/Item.cshtml.cs
using Belcukerkka.Models.Entities;
using Belcukerkka.Models.ViewModels;
using Belcukerkka.Repositories.Interfaces;
using Belcukerkka.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication.Pages.Catalog
{
    public class ItemModel : PageModel
    {
        private readonly IEntityRepository<Box> _boxRepository;
        private readonly ICatalogItemRepository _catalogitemRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ItemModel(IEntityRepository<Box> boxRepository,
            ICatalogItemRepository catalogitemRepository,
            IWebHostEnvironment webHostEnvironment)
        {
            _boxRepository = boxRepository;
            _catalogitemRepository = catalogitemRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        public Box Box { get; set; }

        [BindProperty]
        public int Amount { get; set; }

        public CatalogItemViewModel CatalogItemModel { get; set; }

        public IActionResult OnGet(string box, int weight, int boxId, string composition)
        {
            if (_webHostEnvironment.EnvironmentName == "Staging" && !User.Identity.IsAuthenticated)
                return RedirectToPage("/Maintain");

            Box = _boxRepository.GetWithDependencies(boxId);

            var catalogItem = _catalogitemRepository.Get(Box.BoxParentId, Box.Composition.Weight);
            CatalogItemModel = CatalogItemConverter.ConvertSingleCatalogItem(catalogItem);

            return Page();
        }
    }
}

03 PL/WebApplication/Pages/Catalog/Index.cshtml
@page
@model WebApplication.Pages.Catalog.IndexModel
@{
    ViewData["Title"] = "Каталог";

    string isFiltered = (bool)ViewData["IsFiltered"] ? "checked" : "";
    bool noResults = Model.CatalogItems.Count() == 0;
}

@section Canonical
{
    <link rel="canonical" href="https://belcukerkka.by/catalog" />
}

@Html.AntiForgeryToken()

<div class="cs-container">
    <form method="get">
        <input type="checkbox" hidden disabled class="filter-toggle" title="filter-toggle" @isFiltered>
        <div class="cs-filter-section">
            <label class="cs-filter-label cs-font-primary">Вес подарка:</label>
            <div class="cs-filter-weight">
                @{
                    var arr = (int[])ViewData["WeightsFilter"];
                    string isChecked = string.Empty;
                }

                @for (int i = 0; i < Model.AvailableWeights.Count(); i++)
                {
                    if (arr != null)
                        isChecked = arr.Contains(Model.AvailableWeights.ElementAt(i)) ? "checked" : "";

                    <div class="cs-filter-weight-item">
                        <input type="checkbox" class="cs-checkbox" id="checkbox-weight-@Model.AvailableWeights.ElementAt(i)"
                               value="@Model.AvailableWeights.ElementAt(i)" name="weights" @isChecked>
                        <label class="cs-filter-weight-item__label cs-font-primary" for="checkbox-weight-@Model.AvailableWeights.ElementAt(i)">
                            @Model.AvailableWeights.ElementAt(i)
                        </label>
                    </div>
                }
            </div>
            <label class="cs-filter-label cs-font-primary">Цена:</label>
            <div class="cs-filter-price">
                <span class="cs-filter-price__text cs-font-primary">от</span>
                <input type="number" step="any" name="minPrice" class="cs-filter-price__min cs-form-control input-decimal"
                       placeholder="@Model.MinPrice" value="@ViewData["MinPriceFilter"]">
                <span class="cs-filter-price__text cs-font-primary">до</span>
                <input type="number" step="any" name="maxPrice" class="cs-filter-price__max cs-form-control input-decimal"
                       placeholder="@Model.MaxPrice" value="@ViewData["MaxPriceFilter"]" />
            </div>
            <div class="cs-button-container">
                <button class="cs-btn cs-btn-primary filter-submit" type="submit">ПРИМЕНИТЬ ФИЛЬТРЫ</button>
                <a class="cs-btn cs-btn-primary filter-reset" asp-page="/Catalog/Index">СБРОСИТЬ ФИЛЬТРЫ</a>
            </div>
        </div>
    </form>
</div>

<div class="cs-product-grid" id="catalog">
    @foreach (var item in Model.CatalogItems)
    {
        <partial name="_DisplayCatalogItemPartial" model="item" view-data="ViewData" />
    }
    <span id="product-border" style="display: none"></span>
</div>

@if (noResults)
{
    <div class="cs-filter-no-results">
        <p class="cs-font-red cs-font-primary">По Вашему запросу ничего не найдено. Пожалуйста, измените критерии фильтрации.</p>
    </div>
}

@if (!Model.EveryItemIsLoaded)
{
    <div class="cs-container">
        <div class="cs-button-container cs-button-container-bottom">
            <button class="cs-btn cs-btn-danger" id="load-more">ЕЩЁ ТОВАРЫ</button>
        </div>
    </div>
}

@section Scripts
{
    <script src="~/js/candyshop/catalog.min.js" asp-append-version="true"></script>
}

03 PL/WebApplication/Pages/Catalog/Item.cshtml
@page
@model WebApplication.Pages.Catalog.ItemModel
@{
    var imagePath = "~/images/boxes/" + (Model.Box.BoxParent.ImagePath ?? "noimage.jpg");
    ViewData["Title"] = Model.Box.BoxParent.Name + ", " + Model.Box.Composition.Weight + " гр.";

    var fullPrice = ((double)Model.Box.FullPrice).ToString("0.00");
}

<div class="cs-container">
    <div class="cs-single-product">
        <div class="cs-single-product__title cs-text-center">
            <span class="cs-font-primary cs-font-xl cs-dashed">@Model.Box.BoxParent.Name</span>
        </div>
        <div class="cs-single-product-grid">
            <img src="@imagePath" class="cs-single-product__image" asp-append-version="true">

            <div class="cs-single-product__info">
                <p class="cs-font-primary cs-font-lg cs-font-red">Информация о товаре</p>
                <p class="cs-font-primary">Вес: @Model.Box.Composition.Weight грамм</p>
                <span class="cs-font-primary">Цена: </span>
                <span class="cs-font-primary cs-font-red">@Model.Box.Price.ToString("0.00") руб.</span>
                <span class="cs-font-primary cs-font-sm"><del>(@fullPrice руб.)</del></span>
            </div>

            <div class="cs-single-product__compositions">
                <p class="cs-font-primary cs-font-lg cs-font-red">Состав подарка:</p>
                <div class="cs-button-container-inline">
                    @foreach (var item in Model.CatalogItemModel.Children)
                    {
                        if (item.ChildId != Model.Box.Id)
                        {
                            <a class="cs-btn cs-btn-primary" asp-page="/Catalog/Item"
                               asp-route-box="@item.NameTransliterated" asp-route-weight="@Model.Box.Composition.Weight"
                               asp-route-boxId="@item.ChildId" asp-route-composition="@item.WeightTypeNameTransliterated">
                                @item.WeightTypeName.ToUpperInvariant()
                            </a>
                        }
                        else
                        {
                            <a class="cs-btn cs-btn-primary" disabled>
                                @item.WeightTypeName.ToUpperInvariant()
                            </a>
                        }
                    }
                </div>
            </div>

            <div class="cs-single-product__cart">
                <form method="post" asp-page="/Cart" asp-page-handler="AddToCart" asp-route-boxId="@Model.Box.Id">
                    <div class="cs-input-group">
                        <div class="cs-input-group-item">
                            <button type="button" class="cs-btn cs-btn-secondary cs-btn-minus">
                                <i class="bi bi-dash-lg"></i>
                            </button>
                            <input type="number" id="quantity-0" class="cs-form-control input-number" aria-label="quantity" value="1"
                                   min="1" max="@int.MaxValue" asp-for="Amount">
                            <button type="button" class="cs-btn cs-btn-secondary cs-btn-plus">
                                <i class="bi bi-plus-lg"></i>
                            </button>
                        </div>
                        <div class="cs-input-group-item">
                            <button type="submit" class="cs-btn cs-btn-danger">ДОБАВИТЬ В КОРЗИНУ</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="cs-single-product-candies">
            <div class="cs-single-product-candies__title cs-font-primary cs-font-lg-half">
                <span>КОНФЕТЫ В <br /> ПОДАРКЕ</span>
            </div>
            <div class="cs-single-product-candies__grid">
                @{
                    var candies = Model.Box.Composition.Candies
                        .OrderByDescending(c => c.Name.StartsWith("Шоколад"))
                        .ThenBy(c => c.Name);
                }

                @foreach (var item in candies)
                {
                    var quantity = item.CandyInCompositions
                        .FirstOrDefault(cic => cic.CandyId == item.Id && cic.CompositionId == Model.Box.Composition.Id)
                        .Amount;

                    <div class="cs-candy">
                        <img src="~/images/candies/@item.ImagePath" class="cs-candy-image" asp-append-version="true">
                        <div class="cs-candy-info">
                            <p class="cs-font-primary cs-font-lg-half cs-font-red">@item.Name</p>
                            <p class="cs-font-primary">@item.Description</p>
                        </div>
                        <div class="cs-candy-quantity сs-font-primary cs-font-red">@quantity шт.</div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}